### ISSUE TITLE
callWaiter sometimes does not return a Promise

### ISSUE THREAD

**Issue by seesleestak** [hixme/redux-waiter#35]
I've been running into an error that appears to be related to usage of the waiter with `redux-persist`, but is difficult to reproduce consistently. Occasionally, calls to `callWaiter` will crash the application when we try to perform promise handling (`.then()`, `.catch()`, etc.) on the dispatch. This makes me think there is case when `callWaiter` doesn't return a promise.
 
Looking through the `callWaiter` action, the only thing that looks to be doing that is this bit:
https://github.com/hixme/redux-waiter/blob/master/src/actions.js#L100

What case was this block intended to handle? Are we able to return `requestCreator` here to ensure we're still returning a promise? If not, is there anything more appropriate to return here?

**Comment by billyxs** [comment]
Pretty sure this has to do with `redux-persist` stringifying the store, and in effect mutating it. Not awesome, but it's probably not common to store functions in redux. Since we have a Promise in the store, it gets stringified to an empty object.  Added a check that the request has a `then` available for this case. 

Published a `0.4.3-alpha.0` with a fix if you want to try it out.

**Comment by seesleestak** [comment]
I didn't think it was possible to functions in the store. When I've tried in the past, I think redux strips the property out because the function can't be serialized.

**Comment by billyxs** [comment]
The `requestCreator` and the `request` reside in the store. I understand that's not recommended or a best practice, but that's where it is currently.

**Comment by seesleestak** [comment]
I guess I'm really just confused as to how it's working currently. I tried putting a function reference in redux in a sample project and redux wouldn't let me. The reading I've done seems to indicate it has to be serialized with `toString` before you'll even be able to put it in the store. Since we're not doing this, I don't understand how we're able to get that request out of the store.

On a different note, since the function for the `requestCreator` is always (?) passed in for `callWaiter` and `connectWaiter`, are we able to get it from params instead of off the `getWaiter`?

**Comment by billyxs** [comment]
Many ideas that were implemented for this began back in 2015, and were left relatively unchanged. Documentation and discussion were a bit different, and that documentation is missing these days. eg: https://stackoverflow.com/a/40941428 

I can't speak to what you are currently seeing. I know a lot has evolved since the early days of redux, and I would probably be looking at redux-saga or redux-observable these days if I were to start over with implementing redux.  

It's not required for the `requestCreator` to always be present in `callWaiter`. After the initial call, it would be sufficient to dispatch a `callWaiter` to refresh the data. Much of what is going on in `callWaiter` is meant to keep all components using the same waiter name in sync. This can all be unwound and revamp to adhere the more current standards.

**Comment by seesleestak** [comment]
Ah, looks like that bit in the FAQ is still there. https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

Perhaps it’s only the dev tools that’s not showing functions, but that they’re in the _actual_ store.

Thanks
